package jabcode

import (
	"image/png"
	"os"
	"testing"

	"github.com/srlehn/jabcode/internal/testutil"
)

// TestDecodeCEncoded decodes a PNG produced by the C reference writer, proving
// C-encode -> Go-decode interoperability. The fixture is generated by the C
// jabcodeWriter; the test skips if it is absent.
func TestDecodeCEncoded(t *testing.T) {
	f, err := os.Open(testutil.TestdataPath("c_encoded.png"))
	if err != nil {
		t.Skip("no C-encoded fixture present")
	}
	defer f.Close()
	img, err := png.Decode(f)
	if err != nil {
		t.Fatalf("decode png: %v", err)
	}
	got, err := Decode(img)
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}
	if want := "Encoded by C, decoded by Go"; string(got) != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

// TestDecodeFourColor round-trips 4-color symbols (which always use non-default
// mode) across several ECC levels.
func TestDecodeFourColor(t *testing.T) {
	const s = "Four-color JAB Code round-trip 0123456789"
	for _, level := range []int{0, 2, 5} {
		img, err := NewEncoder(WithColors(4), WithECCLevel(level)).Encode([]byte(s))
		if err != nil {
			t.Errorf("ecc %d encode: %v", level, err)
			continue
		}
		got, err := Decode(img)
		if err != nil {
			t.Errorf("ecc %d decode: %v", level, err)
			continue
		}
		if string(got) != s {
			t.Errorf("ecc %d: got %q, want %q", level, got, s)
		}
	}
}

// TestDecodeNonDefaultECC round-trips 8-color symbols at non-default ECC levels,
// which exercise the full metadata Part I/II path and penalty-based masking.
func TestDecodeNonDefaultECC(t *testing.T) {
	const s = "Non-default ECC level test 12345"
	for _, level := range []int{1, 2, 4, 5, 6, 7} {
		img, err := NewEncoder(WithECCLevel(level)).Encode([]byte(s))
		if err != nil {
			t.Errorf("ecc %d encode: %v", level, err)
			continue
		}
		got, err := Decode(img)
		if err != nil {
			t.Errorf("ecc %d decode: %v", level, err)
			continue
		}
		if string(got) != s {
			t.Errorf("ecc %d: got %q, want %q", level, got, s)
		}
	}
}

// TestDecodeCMultiSymbol decodes C-generated two-symbol (docked) JAB Codes,
// exercising the alignment-pattern detection and secondary-symbol decode path
// on every docking side plus the mixed-version, explicit-slave-ECC and
// four-colour variants. Self-round-trips alone could hide an encode/decode
// convention shared in error; these fixtures pin the wire format to the C
// reference. Each subtest skips if its fixture is absent.
func TestDecodeCMultiSymbol(t *testing.T) {
	cases := []struct {
		fixture string
		want    string
	}{
		{"c_multi.png", "This is a longer message that spans two docked JAB Code symbols for testing."},
		{"c_multi_top.png", "C-encoded secondary docked above, decoded by Go."},
		{"c_multi_left.png", "C-encoded secondary docked left, decoded by Go."},
		{"c_multi_right.png", "C-encoded secondary docked right, decoded by Go."},
		{"c_multi_ss_se.png", "C-encoded taller secondary with its own ECC level, decoded by Go."},
		{"c_multi_4c.png", "C-encoded four-colour docked pair, decoded by Go."},
		{"c_multi_ring.png", "C-encoded ring of eight symbols around a hole, decoded by Go."},
	}
	for _, tc := range cases {
		t.Run(tc.fixture, func(t *testing.T) {
			f, err := os.Open(testutil.TestdataPath(tc.fixture))
			if err != nil {
				t.Skip("fixture not present")
			}
			defer f.Close()
			img, err := png.Decode(f)
			if err != nil {
				t.Fatalf("decode png: %v", err)
			}
			got, err := Decode(img)
			if err != nil {
				t.Fatalf("Decode: %v", err)
			}
			if string(got) != tc.want {
				t.Errorf("got %q, want %q", got, tc.want)
			}
		})
	}
}

// TestDecodeRoundTrip encodes text and decodes the resulting image back,
// exercising the whole detector + decoder pipeline.
func TestDecodeRoundTrip(t *testing.T) {
	inputs := []string{
		"HELLO",
		"hello world",
		"Hello, World!",
		"Just Another Bar Code 2024",
		"https://example.com/path?q=1",
		"The quick brown fox jumps over the lazy dog.",
	}
	for _, s := range inputs {
		img, err := NewEncoder().Encode([]byte(s))
		if err != nil {
			t.Fatalf("encode %q: %v", s, err)
		}
		got, err := Decode(img)
		if err != nil {
			t.Errorf("decode %q: %v", s, err)
			continue
		}
		if string(got) != s {
			t.Errorf("round-trip mismatch: got %q, want %q", got, s)
		}
	}
}
