package jabcode

import (
	"image"
	"image/png"
	"os"
	"strings"
	"testing"

	"github.com/srlehn/jabcode/internal/core"
	"github.com/srlehn/jabcode/internal/decode"
	"github.com/srlehn/jabcode/internal/testutil"
	"github.com/srlehn/jabcode/internal/wire"
)

// TestDecodeCEncoded decodes a PNG produced by the C reference writer, proving
// C-encode -> Go-decode interoperability. The fixture is generated by the C
// jabcodeWriter; the test skips if it is absent.
func TestDecodeCEncoded(t *testing.T) {
	if !ProfileLegacy.Available() {
		t.Skip("legacy profile not compiled")
	}
	f, err := os.Open(testutil.TestdataPath("c_encoded.png"))
	if err != nil {
		t.Skip("no C-encoded fixture present")
	}
	defer f.Close()
	img, err := png.Decode(f)
	if err != nil {
		t.Fatalf("decode png: %v", err)
	}
	auto, err := Decode(img)
	if err != nil {
		t.Fatalf("additive Decode: %v", err)
	}
	if want := "Encoded by C, decoded by Go"; string(auto) != want {
		t.Errorf("additive Decode got %q, want %q", auto, want)
	}
	got, err := DecodeWithProfile(img, ProfileLegacy)
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}
	if want := "Encoded by C, decoded by Go"; string(got) != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

// TestDecodeFourColor round-trips 4-color symbols (which always use non-default
// mode) across several ECC levels.
func TestDecodeFourColor(t *testing.T) {
	const s = "Four-color JAB Code round-trip 0123456789"
	for _, level := range []int{0, 2, 5} {
		img, err := NewEncoder(WithColors(4), WithECCLevel(level)).Encode([]byte(s))
		if err != nil {
			t.Errorf("ecc %d encode: %v", level, err)
			continue
		}
		got, err := Decode(img)
		if err != nil {
			t.Errorf("ecc %d decode: %v", level, err)
			continue
		}
		if want := isoReaderTransmissionString(s); string(got) != want {
			t.Errorf("ecc %d: got %q, want %q", level, got, want)
		}
	}
}

// TestDecodeHighColor round-trips the 16- through 256-color extension modes. The
// reference cannot read these (its normalized-RGB classifier collapses the
// intermediate color levels, and it embeds four palette copies where these modes
// need ISO Annex G's two-copy layout to fit), so this is a library-internal
// encode<->decode contract, exercised across payload sizes and ECC levels to cover
// metadata placement, masking and the 128/256-color palette interpolation.
func TestDecodeHighColor(t *testing.T) {
	if !ProfileHighColor.Available() {
		t.Skip("high-color profile not compiled")
	}
	payloads := []string{
		"hi",
		"high-color JAB Code round-trip 0123456789",
		"A longer payload that spans more data modules so the symbol grows past the smallest version and the placement walk is exercised across several bands. 0123456789 abcdefghijklmnopqrstuvwxyz",
	}
	for _, colors := range []int{16, 32, 64, 128, 256} {
		for _, level := range []int{0, 3, 6} {
			for _, s := range payloads {
				img, err := NewEncoder(WithProfile(ProfileHighColor), WithColors(colors), WithECCLevel(level)).Encode([]byte(s))
				if err != nil {
					t.Errorf("colors %d ecc %d encode: %v", colors, level, err)
					continue
				}
				got, err := DecodeWithProfile(img, ProfileHighColor)
				if err != nil {
					t.Errorf("colors %d ecc %d len %d decode: %v", colors, level, len(s), err)
					continue
				}
				if want := isoReaderTransmissionString(s); string(got) != want {
					t.Errorf("colors %d ecc %d: got %q, want %q", colors, level, got, want)
				}
				if colors == 16 && level == 0 && s == payloads[0] {
					auto, err := Decode(img)
					if err != nil || string(auto) != isoReaderTransmissionString(s) {
						t.Errorf("colors %d ecc %d: additive Decode = %q, %v", colors, level, auto, err)
					}
					if _, err := DecodeWithProfile(img, ProfileISO23634); err == nil {
						t.Errorf("colors %d ecc %d: forced ISO accepted a high-color symbol", colors, level)
					}
				}
			}
		}
	}
}

// TestHighColorModePinned checks that a symbol encoded at a given color count is
// actually decoded at that count - not silently downgraded to a mode a byte
// round-trip would still pass. It reads the color mode straight off the decoded
// metadata, which the public Decode does not expose.
func TestHighColorModePinned(t *testing.T) {
	if !ProfileHighColor.Available() {
		t.Skip("high-color profile not compiled")
	}
	for _, colors := range []int{4, 8, 16, 32, 64, 128, 256} {
		img, err := NewEncoder(WithProfile(ProfileHighColor), WithColors(colors), WithModuleSize(1)).Encode([]byte("pin the mode"))
		if err != nil {
			t.Errorf("colors %d encode: %v", colors, err)
			continue
		}
		bm := core.BitmapFromImage(img)
		sym := core.DecodedSymbol{WireProfile: wire.HighColor}
		if ret := decode.DecodePrimary(bm, &sym); ret != core.Success {
			t.Errorf("colors %d: DecodePrimary returned %d", colors, ret)
			continue
		}
		if got := 1 << (sym.Meta.NC + 1); got != colors {
			t.Errorf("colors %d: decoded color mode is %d (NC=%d)", colors, got, sym.Meta.NC)
		}
	}
}

// TestEncodeColorLimits checks the color-count guards: an invalid count is
// rejected, and a multi-symbol code beyond the secondary palette limit is rejected
// (with the expected message) rather than panicking. Every single-symbol count up
// to 256 is accepted - covered by TestDecodeHighColor.
func TestEncodeColorLimits(t *testing.T) {
	if _, err := NewEncoder(WithColors(7)).Encode([]byte("x")); err == nil {
		t.Error("colors 7: expected an invalid-color-number error, got none")
	}
	if !ProfileHighColor.Available() {
		return
	}
	for _, colors := range []int{64, 128, 256} {
		multi := NewEncoder(WithProfile(ProfileHighColor), WithColors(colors), WithSymbols(
			[]int{0, 2}, []image.Point{{X: 4, Y: 4}, {X: 4, Y: 4}}, []int{0, 0}))
		_, err := multi.Encode([]byte("x"))
		if err == nil || !strings.Contains(err.Error(), "multi-symbol") {
			t.Errorf("multi-symbol colors %d: want a multi-symbol color-limit error, got %v", colors, err)
		}
	}
}

// TestDecodeNonDefaultECC round-trips 8-color symbols at non-default ECC levels,
// which exercise the full metadata Part I/II path and penalty-based masking.
func TestDecodeNonDefaultECC(t *testing.T) {
	const s = "Non-default ECC level test 12345"
	for _, level := range []int{1, 2, 4, 5, 6, 7} {
		img, err := NewEncoder(WithECCLevel(level)).Encode([]byte(s))
		if err != nil {
			t.Errorf("ecc %d encode: %v", level, err)
			continue
		}
		got, err := Decode(img)
		if err != nil {
			t.Errorf("ecc %d decode: %v", level, err)
			continue
		}
		if want := isoReaderTransmissionString(s); string(got) != want {
			t.Errorf("ecc %d: got %q, want %q", level, got, want)
		}
	}
}

// TestDecodeCMultiSymbol decodes C-generated two-symbol (docked) JAB Codes,
// exercising the alignment-pattern detection and secondary-symbol decode path
// on every docking side plus the mixed-version, explicit-slave-ECC and
// four-colour variants. Self-round-trips alone could hide an encode/decode
// convention shared in error; these fixtures pin the wire format to the C
// reference. Each subtest skips if its fixture is absent.
func TestDecodeCMultiSymbol(t *testing.T) {
	if !ProfileLegacy.Available() {
		t.Skip("legacy profile not compiled")
	}
	cases := []struct {
		fixture string
		want    string
	}{
		{"c_multi.png", "This is a longer message that spans two docked JAB Code symbols for testing."},
		{"c_multi_top.png", "C-encoded secondary docked above, decoded by Go."},
		{"c_multi_left.png", "C-encoded secondary docked left, decoded by Go."},
		{"c_multi_right.png", "C-encoded secondary docked right, decoded by Go."},
		{"c_multi_ss_se.png", "C-encoded taller secondary with its own ECC level, decoded by Go."},
		{"c_multi_4c.png", "C-encoded four-colour docked pair, decoded by Go."},
		{"c_multi_ring.png", "C-encoded ring of eight symbols around a hole, decoded by Go."},
	}
	for _, tc := range cases {
		t.Run(tc.fixture, func(t *testing.T) {
			f, err := os.Open(testutil.TestdataPath(tc.fixture))
			if err != nil {
				t.Skip("fixture not present")
			}
			defer f.Close()
			img, err := png.Decode(f)
			if err != nil {
				t.Fatalf("decode png: %v", err)
			}
			got, err := DecodeWithProfile(img, ProfileLegacy)
			if err != nil {
				t.Fatalf("Decode: %v", err)
			}
			if string(got) != tc.want {
				t.Errorf("got %q, want %q", got, tc.want)
			}
		})
	}
}

// TestDecodeExplicitVersion round-trips single symbols whose version is fixed
// by the caller instead of auto-fitted, including rectangular ones.
func TestDecodeExplicitVersion(t *testing.T) {
	const s = "explicit version round-trip 0123456789"
	for _, v := range []image.Point{{X: 8, Y: 8}, {X: 2, Y: 6}, {X: 6, Y: 2}, {X: 12, Y: 4}} {
		img, err := NewEncoder(WithSymbols([]int{0}, []image.Point{v}, []int{0})).Encode([]byte(s))
		if err != nil {
			t.Errorf("version %dx%d encode: %v", v.X, v.Y, err)
			continue
		}
		wantW := (17 + v.X*4) * 12
		wantH := (17 + v.Y*4) * 12
		if b := img.Bounds(); b.Dx() != wantW || b.Dy() != wantH {
			t.Errorf("version %dx%d: image %dx%d, want %dx%d", v.X, v.Y, b.Dx(), b.Dy(), wantW, wantH)
		}
		got, err := Decode(img)
		if err != nil {
			t.Errorf("version %dx%d decode: %v", v.X, v.Y, err)
			continue
		}
		if want := isoReaderTransmissionString(s); string(got) != want {
			t.Errorf("version %dx%d: got %q, want %q", v.X, v.Y, got, want)
		}
	}
}

// TestDecodeRoundTrip encodes text and decodes the resulting image back,
// exercising the whole detector + decoder pipeline.
func TestDecodeRoundTrip(t *testing.T) {
	inputs := []string{
		"HELLO",
		"hello world",
		"Hello, World!",
		"Just Another Bar Code 2024",
		"https://example.com/path?q=1",
		"The quick brown fox jumps over the lazy dog.",
	}
	for _, s := range inputs {
		img, err := NewEncoder().Encode([]byte(s))
		if err != nil {
			t.Fatalf("encode %q: %v", s, err)
		}
		got, err := Decode(img)
		if err != nil {
			t.Errorf("decode %q: %v", s, err)
			continue
		}
		if want := isoReaderTransmissionString(s); string(got) != want {
			t.Errorf("round-trip mismatch: got %q, want %q", got, want)
		}
	}
}
